### ISSUE TITLE
Adding exported files outside of sketch?

### ISSUE THREAD

**Issue by DrDub** [andrewtavis/society#5]
I understand Sketch is convenient for authorship but exported files can be useful for people not using that service. Any chance to add exported versions in PDF or SVG?

**Comment by andrewtavis** [comment]
Hi, thanks for reaching out :) Would be more than happy to add a directory with exports. Will do that right now and add PNGs, PDFs and SVGs.

**Comment by andrewtavis** [comment]
Will close this as the [components](https://github.com/andrewtavis/society/tree/main/components) directory has been set up, but let me know if you'd like any edits to the exports! Would be happy to reopen and change them a bit to fit your needs.

Hope the weekend is going well :)
